namespace Ice.LibClient.Protocol
{
	public enum LocalMsgId
	{
		CCMSG_CONNECTION_READY = 90001,
		CCMSG_CONNECTION_BREAK = 90002,
		CCMSG_CONNECTION_FAILURE = 90003,
		CCMSG_CONNECTION_SEND_FAILURE = 90004,
		CCMSG_CONNECTION_RECV_FAILURE = 90005
	}
}
