namespace Ice.SampleGame.LibClient
{
	public enum LoginByAuthTokenResoult
	{
		GAMESERVER_AUTHLOGIN_RESULT_OK = 0,
		GAMESERVER_AUTHLOGIN_RESULT_UNKNOWN = -1,
		GAMESERVER_AUTHLOGIN_RESULT_NOTLOGINABLE = -2,
		GAMESERVER_AUTHLOGIN_RESULT_NOGS = -3,
		GAMESERVER_AUTHLOGIN_RESULT_CLIENTVERSION = -4
	}
}
