namespace Ice.SampleGame.LibClient
{
	public enum LoginBySessionTokenResoult
	{
		GAMESERVER_SESSIONLOGIN_RESULT_OK = 0,
		GAMESERVER_SESSIONLOGIN_RESULT_UNKNOWN = -1,
		GAMESERVER_SESSIONLOGIN_RESULT_VERIFYFAIL = -2,
		GAMESERVER_SESSIONLOGIN_RESULT_WRONGSERVER = -3,
		GAMESERVER_SESSIONLOGIN_RESULT_LOGINCONFLICT = -4,
		GAMESERVER_SESSIONLOGIN_RESULT_SESSIONTIMEOUT = -5,
		GAMESERVER_SESSIONLOGIN_RESULT_CLIENTVERSION = -6,
		GAMESERVER_SESSIONLOGIN_RESULT_PLAYERBLOCK = -7,
		GAMESERVER_SESSIONLOGIN_RESULT_ONLINECOUNT_MAX = -8
	}
}
